export const filterBoxData = [
  {
    name: 'All',
    isSelected: true,
  },
  {
    name: 'Completed',
    isSelected: false,
  },
  {
    name: 'Pending',
    isSelected: false,
  },
];

export const appointmentDetails = [
  {
    id: '1230458345834',
    drName: 'Dr. Pradip Sharma',
    patientName: 'Rajkrishna Rana',
    date: '17th Oct, 2024',
    time: '12.15 pm',
    status: 'Completed',
    imgSrc: '../assets/images/lady_doctor.png',
  },
  {
    id: '1230458345834',
    drName: 'Dr. Pradip Sharma',
    patientName: 'Rajkrishna Rana',
    date: '17th Oct, 2024',
    time: '12.15 pm',
    status: 'Pending',
    imgSrc: '../assets/images/lady_doctor.png',
  },
  {
    id: '1230458345834',
    drName: 'Dr. Pradip Sharma',
    patientName: 'Rajkrishna Rana',
    date: '17th Oct, 2024',
    time: '12.15 pm',
    status: 'Completed',
    imgSrc: '../assets/images/lady_doctor.png',
  },
  {
    id: '1230458345834',
    drName: 'Dr. Pradip Sharma',
    patientName: 'Rajkrishna Rana',
    date: '17th Oct, 2024',
    time: '12.15 pm',
    status: 'Completed',
    imgSrc: '../assets/images/lady_doctor.png',
  },
  {
    id: '1230458345834',
    drName: 'Dr. Pradip Sharma',
    patientName: 'Rajkrishna Rana',
    date: '17th Oct, 2024',
    time: '12.15 pm',
    status: 'Completed',
    imgSrc: '../assets/images/lady_doctor.png',
  },
  {
    id: '1230458345834',
    drName: 'Dr. Pradip Sharma',
    patientName: 'Rajkrishna Rana',
    date: '17th Oct, 2024',
    time: '12.15 pm',
    status: 'Completed',
    imgSrc: '../assets/images/lady_doctor.png',
  },
  {
    id: '1230458345834',
    drName: 'Dr. Pradip Sharma',
    patientName: 'Rajkrishna Rana',
    date: '17th Oct, 2024',
    time: '12.15 pm',
    status: 'Completed',
    imgSrc: '../assets/images/lady_doctor.png',
  },
  {
    id: '1230458345834',
    drName: 'Dr. Pradip Sharma',
    patientName: 'Rajkrishna Rana',
    date: '17th Oct, 2024',
    time: '12.15 pm',
    status: 'Pending',
    imgSrc: '../assets/images/lady_doctor.png',
  },
  {
    id: '1230458345834',
    drName: 'Dr. Pradip Sharma',
    patientName: 'Rajkrishna Rana',
    date: '17th Oct, 2024',
    time: '12.15 pm',
    status: 'Completed',
    imgSrc: '../assets/images/lady_doctor.png',
  },
  {
    id: '1230458345834',
    drName: 'Dr. Pradip Sharma',
    patientName: 'Rajkrishna Rana',
    date: '17th Oct, 2024',
    time: '12.15 pm',
    status: 'Completed',
    imgSrc: '../assets/images/lady_doctor.png',
  },
  {
    id: '1230458345834',
    drName: 'Dr. Pradip Sharma',
    patientName: 'Rajkrishna Rana',
    date: '17th Oct, 2024',
    time: '12.15 pm',
    status: 'Completed',
    imgSrc: '../assets/images/lady_doctor.png',
  },
  {
    id: '1230458345834',
    drName: 'Dr. Pradip Sharma',
    patientName: 'Rajkrishna Rana',
    date: '17th Oct, 2024',
    time: '12.15 pm',
    status: 'Completed',
    imgSrc: '../assets/images/lady_doctor.png',
  },
  {
    id: '1230458345834',
    drName: 'Dr. Pradip Sharma',
    patientName: 'Rajkrishna Rana',
    date: '17th Oct, 2024',
    time: '12.15 pm',
    status: 'Completed',
    imgSrc: '../assets/images/lady_doctor.png',
  },
  {
    id: '1230458345834',
    drName: 'Dr. Pradip Sharma',
    patientName: 'Rajkrishna Rana',
    date: '17th Oct, 2024',
    time: '12.15 pm',
    status: 'Pending',
    imgSrc: '../assets/images/lady_doctor.png',
  },
  {
    id: '1230458345834',
    drName: 'Dr. Pradip Sharma',
    patientName: 'Rajkrishna Rana',
    date: '17th Oct, 2024',
    time: '12.15 pm',
    status: 'Completed',
    imgSrc: '../assets/images/lady_doctor.png',
  },
  {
    id: '1230458345834',
    drName: 'Dr. Pradip Sharma',
    patientName: 'Rajkrishna Rana',
    date: '17th Oct, 2024',
    time: '12.15 pm',
    status: 'Completed',
    imgSrc: '../assets/images/lady_doctor.png',
  },
  {
    id: '1230458345834',
    drName: 'Dr. Pradip Sharma',
    patientName: 'Rajkrishna Rana',
    date: '17th Oct, 2024',
    time: '12.15 pm',
    status: 'Completed',
    imgSrc: '../assets/images/lady_doctor.png',
  },
  {
    id: '1230458345834',
    drName: 'Dr. Pradip Sharma',
    patientName: 'Rajkrishna Rana',
    date: '17th Oct, 2024',
    time: '12.15 pm',
    status: 'Completed',
    imgSrc: '../assets/images/lady_doctor.png',
  },
  {
    id: '1230458345834',
    drName: 'Dr. Pradip Sharma',
    patientName: 'Rajkrishna Rana',
    date: '17th Oct, 2024',
    time: '12.15 pm',
    status: 'Pending',
    imgSrc: '../assets/images/lady_doctor.png',
  },
  {
    id: '1230458345834',
    drName: 'Dr. Pradip Sharma',
    patientName: 'Rajkrishna Rana',
    date: '17th Oct, 2024',
    time: '12.15 pm',
    status: 'Completed',
    imgSrc: '../assets/images/lady_doctor.png',
  },
  {
    id: '1230458345834',
    drName: 'Dr. Pradip Sharma',
    patientName: 'Rajkrishna Rana',
    date: '17th Oct, 2024',
    time: '12.15 pm',
    status: 'Completed',
    imgSrc: '../assets/images/lady_doctor.png',
  },
  {
    id: '1230458345834',
    drName: 'Dr. Pradip Sharma',
    patientName: 'Rajkrishna Rana',
    date: '17th Oct, 2024',
    time: '12.15 pm',
    status: 'Completed',
    imgSrc: '../assets/images/lady_doctor.png',
  },
];
