
auth.token=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

defaults.org=illimitable-consulting-pvt-ltd
defaults.project=tealink-attendance-react-native

defaults.url=https://sentry.io/
