// GooglePlacesAutocompleteProps.ts
import { GooglePlacesAutocompleteProps } from 'react-native-google-places-autocomplete';

export const GooglePlacesAutocompleteDefaultProps: GooglePlacesAutocompleteProps = {
    autoFillOnNotFound: false,
    currentLocation: false,
    currentLocationLabel: 'Current location',
    debounce: 0,
    disableScroll: false,
    enableHighAccuracyLocation: true,
    enablePoweredByContainer: true,
    fetchDetails: false,
    filterReverseGeocodingByTypes: [],
    GooglePlacesDetailsQuery: {},
    GooglePlacesSearchQuery: {
        rankby: 'distance',
        type: 'restaurant',
    },
    GoogleReverseGeocodingQuery: {},
    isRowScrollable: true,
    keyboardShouldPersistTaps: 'always',
    listHoverColor: '#ececec',
    listUnderlayColor: '#c8c7cc',
    listViewDisplayed: 'auto',
    keepResultsAfterBlur: false,
    minLength: 0,
    nearbyPlacesAPI: 'GooglePlacesSearch',
    numberOfLines: 1,
    onFail: () => {},
    onNotFound: () => {},
    onPress: () => {},
    onTimeout: () => console.warn('google places autocomplete: request timeout'),
    placeholder: '',
    predefinedPlaces: [],
    predefinedPlacesAlwaysVisible: false,
    query: {
        key: 'missing api key',
        language: 'en',
        types: 'geocode',
    },
    styles: {},
    suppressDefaultStyles: false,
    textInputHide: false,
    textInputProps: {},
    timeout: 20000,
    isNewPlacesAPI: false,
    fields: '*',
};
